### ISSUE TITLE
IDRAC &  ILO - Service 

### ISSUE THREAD

**Issue by EWANZO101** [Veloxbill/tracker#15] opened 2024-07-02 08:08 UTC
### Describe the solution you'd like

Ability to control physical servers and sell them via the Velox panel, with the option to add as many servers as you like 

### Additional context

https://developer.hpe.com/platform/ilo-restful-api/home/

https://www.dell.com/support/kbdoc/en-uk/000178045/redfish-api-with-dell-integrated-remote-access-controller

**Comment by SiFuMax09** [comment] 2024-07-02 14:19
Duplicate of #2

**Closed by SiFuMax09** 2024-07-02 14:19 UTC
Labels: enhancement, Service
